@HousingApi_HostAddress = http://localhost:5125

GET {{HousingApi_HostAddress}}/api/locations
Accept: application/json

###

GET {{HousingApi_HostAddress}}/api/locations/replace-with-object-id
Accept: application/json

###
